# Generated by Django 5.2 on 2025-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_landingpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_us_ch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_us_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_us_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_us_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_us_hs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_us_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='about_us_yb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_address_ch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_address_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_address_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_address_hs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_address_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_address_yb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_subtitle_ch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_subtitle_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_subtitle_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_subtitle_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_subtitle_hs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_subtitle_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_subtitle_yb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_title_ch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_title_hs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_title_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='hero_title_yb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='what_we_do_ch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='what_we_do_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='what_we_do_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='what_we_do_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='what_we_do_hs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='what_we_do_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='what_we_do_yb',
            field=models.TextField(null=True),
        ),
    ]
