# Generated by Django 5.2 on 2025-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_landingpagecontent_about_us_ch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_email_ch',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_email_en',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_email_es',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_email_fr',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_email_hs',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_email_ig',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_email_yb',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_phone_ch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_phone_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_phone_es',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_phone_fr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_phone_hs',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_phone_ig',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_phone_yb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us_ch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us_hs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us_ig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='contact_us_yb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
