# Generated by Django 5.2 on 2025-06-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('salesperson', 'Salesperson')], default='salesperson', max_length=50),
        ),
    ]
