# Generated by Django 5.2 on 2025-06-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sales Dashboard', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
            ],
        ),
    ]
