# Generated by Django 5.2 on 2025-07-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('salesperson', 'Salesperson')], max_length=20),
        ),
    ]
