# Generated by Django 5.2 on 2025-06-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topcustomer',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.customer'),
            preserve_default=False,
        ),
    ]
