# Generated by Django 5.2 on 2025-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestarget',
            name='daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
