# Generated by Django 5.2 on 2025-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_saleitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysalesdata',
            name='purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklysalesdata',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
