# Generated by Django 5.2 on 2025-06-18 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_weeklysalesdata_purchases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year_target', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
