# Generated by Django 5.2 on 2025-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_rename_product_quality_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsellingproduct',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topsellingproduct',
            name='quantity_sold',
            field=models.PositiveIntegerField(),
        ),
    ]
