# Generated by Django 5.2 on 2025-06-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pos', '0006_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='exchange_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
