# Generated by Django 5.2 on 2025-06-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_topsellingproduct_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_alert',
        ),
        migrations.RemoveField(
            model_name='salestarget',
            name='month_target',
        ),
        migrations.RemoveField(
            model_name='salestarget',
            name='week_target',
        ),
        migrations.RemoveField(
            model_name='salestarget',
            name='year_target',
        ),
        migrations.AddField(
            model_name='salestarget',
            name='monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
