# Generated by Django 5.2 on 2025-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_sale_exchange_for_sale_is_exchange_sale_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='quantity',
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
