# Generated by Django 5.2 on 2025-06-25 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_remove_salesreturn_date_remove_salesreturn_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'permissions': [('can_apply_discount', 'Can apply discount to products')]},
        ),
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
