# Generated by Django 5.2 on 2025-06-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockalert_product'),
        ('pos', '0009_alter_discount_options_discount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_stock_alerts', to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
