# Generated by Django 5.2 on 2025-07-01 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
