# Generated by Django 5.2 on 2025-07-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_salesreturn_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
